name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@01524fade784327df1a5ad1ead94235d392cd443 # v2
      - name: Build to `dist/`
        run: deno run -A ./main.ts
      - name: Create Release
        uses: suzuki-shunsuke/release-js-action@d824154e854ff4bfd1f87dc70f01ca3a50009ad1 # v0.1.3
        with:
          version: latest
